-- 00_create_topics.sql
-- Idempotent creation of TOPICS table (Oracle 19c OK).
SET DEFINE OFF;
BEGIN
  BEGIN
    EXECUTE IMMEDIATE q'(
      CREATE TABLE topics (
        topic_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code       VARCHAR2(64) NOT NULL,
        name_ko    VARCHAR2(200) NOT NULL,
        title      VARCHAR2(200),
        body       CLOB,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP
      )
    )';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
  END;
  -- fallback: ensure default via sequence if identity isn't active
  DECLARE v_def VARCHAR2(4000);
  BEGIN
    SELECT data_default INTO v_def
    FROM user_tab_cols
    WHERE table_name='TOPICS' AND column_name='TOPIC_ID';
    IF v_def IS NULL OR INSTR(UPPER(v_def), 'NEXTVAL') = 0 THEN
      BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE topics_id_seq START WITH 1 NOCACHE'; 
      EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
      BEGIN EXECUTE IMMEDIATE 'ALTER TABLE topics MODIFY (topic_id NUMBER DEFAULT topics_id_seq.NEXTVAL NOT NULL)';
      EXCEPTION WHEN OTHERS THEN NULL; END;
    END IF;
  EXCEPTION WHEN NO_DATA_FOUND THEN NULL; END;
END;
/
COMMIT;
